# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ModalClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TokenFlowCreate = channel.unary_unary(
                '/modal.client.ModalClient/TokenFlowCreate',
                request_serializer=api__pb2.TokenFlowCreateRequest.SerializeToString,
                response_deserializer=api__pb2.TokenFlowCreateResponse.FromString,
                _registered_method=True)
        self.TokenFlowWait = channel.unary_unary(
                '/modal.client.ModalClient/TokenFlowWait',
                request_serializer=api__pb2.TokenFlowWaitRequest.SerializeToString,
                response_deserializer=api__pb2.TokenFlowWaitResponse.FromString,
                _registered_method=True)


class ModalClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TokenFlowCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TokenFlowWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModalClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TokenFlowCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenFlowCreate,
                    request_deserializer=api__pb2.TokenFlowCreateRequest.FromString,
                    response_serializer=api__pb2.TokenFlowCreateResponse.SerializeToString,
            ),
            'TokenFlowWait': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenFlowWait,
                    request_deserializer=api__pb2.TokenFlowWaitRequest.FromString,
                    response_serializer=api__pb2.TokenFlowWaitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modal.client.ModalClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModalClient(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TokenFlowCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modal.client.ModalClient/TokenFlowCreate',
            api__pb2.TokenFlowCreateRequest.SerializeToString,
            api__pb2.TokenFlowCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TokenFlowWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modal.client.ModalClient/TokenFlowWait',
            api__pb2.TokenFlowWaitRequest.SerializeToString,
            api__pb2.TokenFlowWaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
